---
- name: Deploy code on servers
  hosts: all
  become: yes
  remote_user: root
  become_user: root

  tasks:
    - name: Start and Enable Tomcat 10 on sever
      systemd:
        name: tomcat
        state: started
        daemon_reload: true