---
- name: Deploy code on servers
  hosts: "{{myHosts}}"
  become: yes
  remote_user: root
  become_user: root

  tasks:
    - name: Copy war file
      copy:
        src: "{{artifact}}"
        dest: /opt/tomcat10/webapps/
        mode: 0755

    - name: Start and Enable Tomcat 10 on sever
      systemd:
        name: tomcat
        state: started
        daemon_reload: true